### ISSUE TITLE
Elements dont quite line up correctly.

### ISSUE THREAD

**Issue by BumpyAHK** [szymonszewcjr/ReasonableYoutubeLayout#1]
Recommended videos and comments show up on their respective sides of the screen, however they are not positioned correctly. First thought was that its due to resolution, but that does not seem to be the case.

![image](https://github.com/szymonszewcjr/ReasonableYoutubeLayout/assets/41409776/d7c9643b-7e3a-4ae5-baf7-455f4fde92ac)

No other Tampermonkey scripts or extensions that edit youtube's layout are installed. Nonetheless this is a great step forward in removing this god awful update, thank you!

**Comment by BumpyAHK** [comment]
Manually switching primary and secondary dividers has the same affect, potentially a me issue.

**Comment by jxzhe** [comment]
Try using the theater mode (press T, or install this [extension](https://chromewebstore.google.com/detail/theater-mode-for-youtube/dgognhgbpdoeidccnbfhohblklhbbomh) to automatically use the theater mode every time)

**Comment by BumpyAHK** [comment]
> Try using the theater mode (press T, or install this [extension](https://chromewebstore.google.com/detail/theater-mode-for-youtube/dgognhgbpdoeidccnbfhohblklhbbomh) to automatically use the theater mode every time)

Unfortunately, while the issue is certainly better, it still persists. The recommended videos are pushed off screen. Thanks for the suggestion though!

**Comment by szymonszewcjr** [comment]
This is pretty much abandonware at this point, youtube seems to have ended the experiment in my region, so I cannot help you with this.
